  name: BabylonTesting
  type: docker
  kind: pipeline
  steps:
    - name: Clone and Test
      image: omerxx/drone-ecr-auth
      pull: true
      privileged: true
      volumes:
        - name: dockersock
          path: /var/run/docker.sock
      environment:
        MPICH_PATH:  /usr/local/mpich3/bin/mpiexec
        NMVERSION: nm74gf
        NONMEM_LICENSE:
            from_secret: NONMEM_LICENSE
        GITHUB_TOKEN:
            from_secret: GITHUB_TOKEN
        AWS_ACCESS_KEY:
            from_secret AWS_ACCESS_KEY
        AWS_SECRET_ACCESS_KEY:
            from_secret: AWS_SECRET_KEY
      commands:
        - $(aws ecr get-login --no-include-email --region us-east-1)
        - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem
        - chmod +x test.sh
        - docker run --rm -t -v /workspace:/app --command="ls -la /" 906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem
        - docker run --rm -t -v /drone/src:/app -e NONMEM_LICENSE="$NONMEM_LICENSE" -e GITHUB_TOKEN="$GITHUB_TOKEN" -e NMVERSION="nm74gf" --entrypoint="/app/test.sh"  906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem
  volumes:
    - name: dockersock
      host:
        path: /var/run/docker.sock
    - name: datadir
      host:
        path: /drone/src/data