  name: BabylonTesting
  type: docker
  kind: pipeline
  steps:
    - name: build image
      environment:
        BBI_BRANCH: $$BRANCH
      image: plugins/docker
      settings:
        username:
          from_secret: DOCKERHUB_USERNAME
        password:
          from_secret: DOCKERHUB_PASSWORD
        repo: dukeofubuntu/babylon
        tags:
          - $$BRANCH
        build_args_from_env:
          - DRONE_BRANCH
    - name: test
      image: dukeofubuntu/babylon:$$BRANCH
      environment:
        MPIEXEC_PATH: /usr/bin/mpiexec
        NONMEMROOT: /opt
        NMVERSION: nm
        NONMEM_LICENSE:
          from_secret: NONMEM_LICENSE
      commands:
        - echo "$NONMEM_LICENSE" > /opt/nm/license/nonmem.lic
        - mkdir /test
        - cd /test
        - git clone https://github.com/metrumresearchgroup/babylontest.git
        - cd babylontest
        - go mod download
        - go test ./... -v

  trigger:
    event:
      - push
