  name: BabylonTesting
  type: docker
  kind: pipeline
  steps:
    - name: pull core image
      image: omerxx/drone-ecr-auth
      volumes:
        - name: docker.sock
          path: /var/run/docker.sock
      commands:
        - $(aws ecr get-login --no-include-email --region us-east-1)
        - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem
    - name: Build updated image
      image: omerxx/drone-ecr-auth
      commands:
        - docker build -t "nmtest" .
      volumes:
        - name: docker.sock
          path: /var/run/docker.sock
    - name: Test
      environment:
        MPIEXEC_PATH: /usr/bin/mpiexec
        NONMEMROOT: /opt/NONMEM
        NMVERSION: nm74gf
        NONMEM_LICENSE:
          from_secret: NONMEM_LICENSE
      image: nmtest
      pull: never
      commands:
        - echo "$NONMEM_LICENSE" > /opt/NONMEM/nm74gf/license/nonmem.lic
        - go test ./... -v

  trigger:
    event:
      - push


  volumes:
    - name: docker.sock
      host:
        path: /var/run/docker.sock