  name: BabylonTesting
  type: docker
  kind: pipeline
  steps:
    - name: Clone and Test
      image: agur/drone-ecr-puller
      access_key:
      secret_access_key:
      region: us-east-1
      environment:
        MPICH_PATH:  /usr/local/mpich3/bin/mpiexec
        NMVERSION: nm74gf
        LICENSE:
            from_secret: NONMEM_LICENSE
        GITHUB_TOKEN:
            from_secret: GITHUB_TOKEN
      commands:
        - git clone https://github.com/metrumresearchgroup/babylontest.git
        - cd babylontest
        - go mod download
        - docker run --rm -it -v $(pwd)/nonmem.lic:/opt/NONMEM/nm74gf/license/nonmem.lic 906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem go test -v ./...