  name: BabylonTesting
  type: docker
  kind: pipeline
  steps:
    - name: build image
      image: plugins/docker
      settings:
        username:
          from_secret: DOCKERHUB_USERNAME
        password:
          from_secret: DOCKERHUB_PASSWORD
        repo: dukeofubuntu/babylon
        tags: ${DRONE_BRANCH}
        build_args:
          - BBI_BRANCH=$$DRONE_BRANCH
    - name: test
      image: dukeofubuntu/babylon:${DRONE_BRANCH}
      environment:
        MPIEXEC_PATH: /usr/bin/mpiexec
        NONMEMROOT: /opt
        NMVERSION: nm
        NONMEM_LICENSE:
          from_secret: NONMEM_LICENSE
      commands:
        - echo "$NONMEM_LICENSE" > /opt/nm/license/nonmem.lic
        - mkdir /test
        - cd /test
        - git clone https://github.com/metrumresearchgroup/babylontest.git
        - cd babylontest
        - go mod download
        - go test ./... -v