  name: BabylonTesting
  type: docker
  kind: pipeline
  steps:
    - name: Clone and Test
      image: agur/drone-ecr-puller
      access_key:
      secret_access_key:
      region: us-east-1
      volumes:
        - name: dockersock
          path: /var/run/docker.sock
      environment:
        MPICH_PATH:  /usr/local/mpich3/bin/mpiexec
        NMVERSION: nm74gf
        LICENSE:
            from_secret: NONMEM_LICENSE
        GITHUB_TOKEN:
            from_secret: GITHUB_TOKEN
      commands:
        - docker run --rm -it -v $(pwd):/app -e LICENSE="${NONMEM_LICENSE}" -e GITHUB_TOKEN="${GITHUB_TOKEN}" 906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem sh /app/test.sh
  volumes:
    - name: dockersock
      host:
        path: /var/run/docker.sock