  name: BabylonTesting
  type: docker
  kind: pipeline
  steps:
    - name: Pull
      image: omerxx/drone-ecr-auth
      pull: true
      privileged: true
      volumes:
        - name: dockersock
          path: /var/run/docker.sock
      environment:
        MPICH_PATH:  /usr/local/mpich3/bin/mpiexec
        NMVERSION: nm74gf
        AWS_ACCESS_KEY:
            from_secret AWS_ACCESS_KEY
        AWS_SECRET_ACCESS_KEY:
            from_secret: AWS_SECRET_KEY
      commands:
        - $(aws ecr get-login --no-include-email --region us-east-1)
        - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem
    - name: Clone and Test
      image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/nonmem
      pull: true
      privileged: true
      environment:
        MPICH_PATH:  /usr/local/mpich3/bin/mpiexec
        NMVERSION: nm74gf
        LICENSE:
          from_secret: NONMEM_LICENSE
        GITHUB_TOKEN:
          from_secret: GITHUB_TOKEN
      commands:
        - echo "Beginning Execution!"
        - sh test.sh
  volumes:
    - name: dockersock
      host:
        path: /var/run/docker.sock